Added error if host is not reachable

diff --git a/nagios/plugins/check_elasticsearch b/nagios/plugins/check_elasticsearch
--- a/nagios/plugins/check_elasticsearch
+++ b/nagios/plugins/check_elasticsearch
@@ -12,7 +12,7 @@
 # Heap crit and warn against average
 # ***REMOVED***:9200/_cat/nodes/?h=name,ram.percent,heap.percent,file_desc.percent,load_5m
 
-VERSION=0.1
+VERSION=0.3
 readonly me=`basename "$0"`
 
 HOST=""
@@ -32,10 +32,15 @@ setup () {
   load_data
 }
 
+error () {
+  echo "ERROR: $1"
+  exit $2
+}
+
 #heap_percent=`curl "***REMOVED***:9200/_cat/nodes?h=heap.percent"`
 
 fetch_data () {
-  fetched_data=$(curl -s "$HOST:$PORT/_cat/nodes?h=name,heap.percent,ram.percent,file_desc.percent,load_15m")
+  fetched_data=$(curl -s "$HOST:$PORT/_cat/nodes?h=name,heap.percent,ram.percent,file_desc.percent,load_15m") || error "Host not found" $?
   local IFS=' '
   local arraypos=0
   while read line; do
